### PR TITLE
👷 Limit max pygit2 version due to breaking changes

### LINKED ISSUE #758: Incompatibility with pygit2 1.15.0
Hi, I recently made a fresh installation of retrocookie and found a problem with pygit2.

```Traceback (most recent call last):
  File "/home/bciconel/.local/bin/retrocookie", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/__main__.py", line 120, in main
    retrocookie(
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/core.py", line 162, in retrocookie
    commits = rewrite_commits(
              ^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/core.py", line 87, in rewrite_commits
    return [repository.lookup_replacement(commit) for commit in commits]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/core.py", line 87, in <listcomp>
    return [repository.lookup_replacement(commit) for commit in commits]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bciconel/.local/pipx/venvs/retrocookie/lib64/python3.11/site-packages/retrocookie/git.py", line 189, in lookup_replacement
    return cast(str, ref.target.hex)
                     ^^^^^^^^^^^^^^
AttributeError: '_pygit2.Oid' object has no attribute 'hex'
```

Manually downgrading `pygit2` fixed the issue here.

### PR DESCRIPTION
**Pull request by bruno-fs**
Limit pygit2 max version to <1.15 due to breaking changes [pygit2-changelog] it introduces.

At least one of the deprecations affects this codebase: `Remove deprecated oid.hex, use str(oid)` (see #758).

Fix #758

PS: I tried to mimick the emojis you use on commit messages, but I'm not sure if I got it it 😅 .

[pygit2-changelog]: https://github.com/libgit2/pygit2/blob/master/CHANGELOG.md#1150-2024-05-18

### CODE REVIEW

**Comment by bruno-fs** [comment]
@cjolowicz, when running pipx locally I was finding the same issue that's happening on CI right now.
Changing to an absolute path solved it locally, so I added a commit including this change.

**Comment by bruno-fs** [comment]
Well, at least the error changed. I guess new errors mean progress, right? 😅 

From the new error the issue is that I used a more up to date version of poetry, which created an incompatible lock file.
Is it ok if I upgrade the dependencies on the constraints file, @cjolowicz ?

**Comment by bruno-fs** [comment]
OK, CI is now finally passing for _almost_ all checks. Only safety is failing now. 5 dependencies would require action, but I'm not sure how you prefer to tackle these kind of issue.

**Comment by cjolowicz** [comment]
Thank you for working on this! I'm fine with upgrading any dependencies that cause errors in Safety or other CI jobs.

**Comment by bruno-fs** [comment]
Wow, what started as a "hey, a single line of code can fix this here" became a visit to dependency hell haha.
It was worth it.

Summary of changes:
- had to drop support to python 3.7 (which is EOL, so I think its fine) in order to bump the affected libraries
- since I was playing with python versions, also updated the support matrix with up to 3.12
- had to adjust the code to play nice with updated linter versions, with exception to type guard. That one I just downgraded back to the version that was in use before because there were more than 20 failures.

All checks passed on my fork (bruno-fs/retrocookie#1)

**Review by cjolowicz — APPROVED** [review]

**Pull request merged**
